/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.suaritma.gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.SQLException;

import javax.swing.JFrame;
import javax.swing.JPanel;

import com.suaritma.controller.MusteriController;
import com.suaritma.database.DatabaseOlustur;

/**
 *
 * @author Toshiba
 */
public class AnaSayfa extends javax.swing.JFrame{
	
	public int x,y;
	public Point point = null;
    
    public AnaSayfa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
  /*  private void initComponents() {

        anaPanel = new javax.swing.JPanel();
        ustPanel = new javax.swing.JPanel();
        anaBaslik = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        stokTakip = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        musteriler = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bildirimler = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        yeniKisiKayit = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hesapBilgi = new JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(20, 20));
        setLocationByPlatform(true);
        setUndecorated(true);

        anaPanel.setBackground(new java.awt.Color(255, 255, 255));
        anaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ustPanel.setBackground(new java.awt.Color(45, 118, 232));
        ustPanel.setToolTipText("");
        ustPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ustPanelMouseDragged(evt);
            }
        });
        ustPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ustPanelMousePressed(evt);
            }
            public void mouseReleased(MouseEvent evt) {
            	ustPanelMouseReleased(evt);
            }
        });
        ustPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        anaBaslik.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        anaBaslik.setForeground(new java.awt.Color(255, 255, 255));
        anaBaslik.setText("SU ARITMA PROGRAMI ");
        ustPanel.add(anaBaslik, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 590, 70));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Water_48px_1.png"))); // NOI18N
        ustPanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 70, 70));

        exit.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        ustPanel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 20, 40));

        jLabelMin.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("_");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        ustPanel.add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 60, 40));

        anaPanel.add(ustPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 880, 190));

        stokTakip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stokTakipMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stokTakipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stokTakipMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Price_Tag_48px.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(45, 118, 232));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 118, 232));
        jLabel2.setText("STOK TAKÝP");

        javax.swing.GroupLayout stokTakipLayout = new javax.swing.GroupLayout(stokTakip);
        stokTakip.setLayout(stokTakipLayout);
        stokTakipLayout.setHorizontalGroup(
            stokTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stokTakipLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(stokTakipLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        stokTakipLayout.setVerticalGroup(
            stokTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stokTakipLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        anaPanel.add(stokTakip, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 200, 130));

        musteriler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musterilerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                musterilerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musterilerMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Conference_48px.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(45, 118, 232));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 118, 232));
        jLabel4.setText("MÜÞTERÝLER");

        javax.swing.GroupLayout musterilerLayout = new javax.swing.GroupLayout(musteriler);
        musteriler.setLayout(musterilerLayout);
        musterilerLayout.setHorizontalGroup(
            musterilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musterilerLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(musterilerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        musterilerLayout.setVerticalGroup(
            musterilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musterilerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        anaPanel.add(musteriler, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 180, 130));

        bildirimler.setToolTipText("");
        bildirimler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bildirimlerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bildirimlerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bildirimlerMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Notification_48px.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(45, 118, 232));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 118, 232));
        jLabel6.setText("BÝLDÝRÝMLER");

        javax.swing.GroupLayout bildirimlerLayout = new javax.swing.GroupLayout(bildirimler);
        bildirimler.setLayout(bildirimlerLayout);
        bildirimlerLayout.setHorizontalGroup(
            bildirimlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bildirimlerLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(bildirimlerLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bildirimlerLayout.setVerticalGroup(
            bildirimlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bildirimlerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        anaPanel.add(bildirimler, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 200, 130));

        yeniKisiKayit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yeniKisiKayitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yeniKisiKayitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yeniKisiKayitMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Add_User_Group_Woman_Man_48px.png"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(45, 118, 232));
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(45, 118, 232));
        jLabel10.setText("YENÝ KÝÞÝ KAYIT");

        javax.swing.GroupLayout yeniKisiKayitLayout = new javax.swing.GroupLayout(yeniKisiKayit);
        yeniKisiKayit.setLayout(yeniKisiKayitLayout);
        yeniKisiKayitLayout.setHorizontalGroup(
            yeniKisiKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniKisiKayitLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yeniKisiKayitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        yeniKisiKayitLayout.setVerticalGroup(
            yeniKisiKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniKisiKayitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        hesapBilgi.setToolTipText("");
        hesapBilgi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hesapBilgiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                //hesapBilgiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                //hesapBilgiMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Money_Bag_48px_1.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(45, 118, 232));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 118, 232));
        jLabel8.setText("   HESAP BÝLGÝ");

        javax.swing.GroupLayout hesapBilgiLayout = new javax.swing.GroupLayout(hesapBilgi);
        hesapBilgi.setLayout(hesapBilgiLayout);
        hesapBilgiLayout.setHorizontalGroup(
            hesapBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hesapBilgiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(hesapBilgiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        hesapBilgiLayout.setVerticalGroup(
            hesapBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesapBilgiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        anaPanel.add(hesapBilgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, 130));

        anaPanel.add(yeniKisiKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 200, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 788, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>       */         
    private void initComponents() {

        anaPanel = new javax.swing.JPanel();
        ustPanel = new javax.swing.JPanel();
        anaBaslik = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        stokTakip = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        musteriler = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bildirimler = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        yeniKisiKayit = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hesapBilgi = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(20, 20));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new Dimension(799, 522));

        anaPanel.setBackground(new java.awt.Color(255, 255, 255));
        anaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ustPanel.setBackground(new java.awt.Color(45, 118, 232));
        ustPanel.setToolTipText("");
        ustPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ustPanelMouseDragged(evt);
            }
        });
        ustPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ustPanelMousePressed(evt);
            }
            public void mouseReleased(MouseEvent evt) {
            	ustPanelMouseReleased(evt);
            }
        });
        ustPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        anaBaslik.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        anaBaslik.setForeground(new java.awt.Color(255, 255, 255));
        anaBaslik.setText("SU ARITMA PROGRAMI ");
        ustPanel.add(anaBaslik, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 590, 70));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Water_48px_1.png"))); // NOI18N
        ustPanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 70, 70));

        exit.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        ustPanel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 20, 40));

        jLabelMin.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("_");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        ustPanel.add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 60, 40));

        anaPanel.add(ustPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 880, 190));

        stokTakip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stokTakipMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stokTakipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stokTakipMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Price_Tag_48px.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(45, 118, 232));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 118, 232));
        jLabel2.setText("STOK TAKÝP");

        javax.swing.GroupLayout stokTakipLayout = new javax.swing.GroupLayout(stokTakip);
        stokTakip.setLayout(stokTakipLayout);
        stokTakipLayout.setHorizontalGroup(
            stokTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stokTakipLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(stokTakipLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        stokTakipLayout.setVerticalGroup(
            stokTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stokTakipLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        anaPanel.add(stokTakip, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 200, 130));

        musteriler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musterilerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                musterilerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musterilerMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Conference_48px.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(45, 118, 232));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 118, 232));
        jLabel4.setText("MÜÞTERÝLER");

        javax.swing.GroupLayout musterilerLayout = new javax.swing.GroupLayout(musteriler);
        musteriler.setLayout(musterilerLayout);
        musterilerLayout.setHorizontalGroup(
            musterilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musterilerLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(musterilerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        musterilerLayout.setVerticalGroup(
            musterilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musterilerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        anaPanel.add(musteriler, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 180, 130));

        bildirimler.setToolTipText("");
        bildirimler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bildirimlerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bildirimlerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bildirimlerMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Notification_48px.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(45, 118, 232));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 118, 232));
        jLabel6.setText("BÝLDÝRÝMLER");

        javax.swing.GroupLayout bildirimlerLayout = new javax.swing.GroupLayout(bildirimler);
        bildirimler.setLayout(bildirimlerLayout);
        bildirimlerLayout.setHorizontalGroup(
            bildirimlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bildirimlerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(bildirimlerLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bildirimlerLayout.setVerticalGroup(
            bildirimlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bildirimlerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        anaPanel.add(bildirimler, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 200, 130));

        yeniKisiKayit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yeniKisiKayitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yeniKisiKayitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yeniKisiKayitMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Add_User_Group_Woman_Man_48px.png"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(45, 118, 232));
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(45, 118, 232));
        jLabel10.setText("YENÝ KÝÞÝ KAYIT");

        javax.swing.GroupLayout yeniKisiKayitLayout = new javax.swing.GroupLayout(yeniKisiKayit);
        yeniKisiKayit.setLayout(yeniKisiKayitLayout);
        yeniKisiKayitLayout.setHorizontalGroup(
            yeniKisiKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniKisiKayitLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yeniKisiKayitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        yeniKisiKayitLayout.setVerticalGroup(
            yeniKisiKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniKisiKayitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        anaPanel.add(yeniKisiKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 200, 130));

        hesapBilgi.setToolTipText("");
        hesapBilgi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hesapBilgiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hesapBilgiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hesapBilgiMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Money_Bag_48px_1.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(45, 118, 232));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 118, 232));
        jLabel8.setText("   HESAP BÝLGÝ");

        javax.swing.GroupLayout hesapBilgiLayout = new javax.swing.GroupLayout(hesapBilgi);
        hesapBilgi.setLayout(hesapBilgiLayout);
        hesapBilgiLayout.setHorizontalGroup(
            hesapBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesapBilgiLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hesapBilgiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        hesapBilgiLayout.setVerticalGroup(
            hesapBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesapBilgiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        anaPanel.add(hesapBilgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 190, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void exitMousePressed(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        System.exit(0);
    }                                 

    private void musterilerMouseEntered(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        setColor(musteriler);
        
    }                                       

    private void musterilerMouseExited(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        resetColor(musteriler);
        
    }                  
    private void hesapBilgiMouseEntered(MouseEvent evt) {
    	setColor(hesapBilgi);
    }
    
    private void hesapBilgiMouseExited(MouseEvent evt) {
    	resetColor(hesapBilgi);
    }

    private void bildirimlerMouseEntered(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
         setColor(bildirimler);
    }                                        

    private void bildirimlerMouseExited(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
         resetColor(bildirimler);
    }                                       

    private void stokTakipMouseEntered(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
         setColor(stokTakip);
    }                                      

    private void stokTakipMouseExited(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
         resetColor(stokTakip);
    }                          
    private void hesapBilgiMouseClicked(MouseEvent evt) {
    	HesapBilgi h1 = new HesapBilgi();
    	h1.setVisible(true);
    }

  
    private void ustPanelMouseDragged(java.awt.event.MouseEvent evt) {                                      
    	Point nokta = evt.getLocationOnScreen();
    	this.setLocation(nokta.x - point.x + 20 , nokta.y - point.y + 30);
      
    }     
    
    private void ustPanelMouseReleased(MouseEvent evt) {
    	point = null;
    }

    private void ustPanelMousePressed(java.awt.event.MouseEvent evt) {                                      
        point = evt.getPoint();
       
    }                                     

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {                                       
        this.setState(JFrame.ICONIFIED);
    }                                      

    private void yeniKisiKayitMouseEntered(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        setColor(yeniKisiKayit);
    }                                          

    private void yeniKisiKayitMouseExited(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        resetColor(yeniKisiKayit);
    }                                         

    private void musterilerMouseClicked(java.awt.event.MouseEvent evt) {                                        
        Musteriler theMusteriler = new Musteriler();
        theMusteriler.setVisible(true);
    }                                       

    private void yeniKisiKayitMouseClicked(java.awt.event.MouseEvent evt) {                                           
    	YeniMusteriKayit theYeniMusteriKayit = new YeniMusteriKayit();
    	theYeniMusteriKayit.setVisible(true);
    }                                          

    private void stokTakipMouseClicked(java.awt.event.MouseEvent evt) {                                       
    	StokTakip theStokTakip = new StokTakip();
    	theStokTakip.setVisible(true);
    }                                      

    private void bildirimlerMouseClicked(java.awt.event.MouseEvent evt) {                                         
    	Bildirimler b1 = new Bildirimler();
    	b1.setVisible(true);
    }                                        

    public void setColor(JPanel panel){
        
        panel.setBackground(new java.awt.Color(205,200,177));
        
                
    }
        public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(240,240,240));
                
    }
    /**
     * @param args the command line arguments
     * @throws SQLException 
     * @throws IOException 
     */
    public static void main(String args[]) throws IOException, SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	
    	DatabaseOlustur databaseOlustur = new DatabaseOlustur();
    	databaseOlustur.executeDBScripts();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaSayfa().setVisible(true);
                
              
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel anaBaslik;
    private javax.swing.JPanel anaPanel;
    private javax.swing.JPanel bildirimler;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel musteriler;
    private javax.swing.JPanel stokTakip;
    private javax.swing.JPanel ustPanel;
    private javax.swing.JPanel yeniKisiKayit;
    private JPanel hesapBilgi;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration                   
}

